export const types = {
  LOGIN: "[auth] login",
  REGISTER: "[auth] register",
  LOGOUT: "[auth] logout",
  GET_USER_DATA: "[auth] get_user_data",
  SAVE_ADDRESS: "[auth] save_address",
  SAVE_PURCHASE: "[auth] save_purchase",
  ADD_NEW_CHOC: "[current] add_new_choc",
  INCREMENT_CHOC: "[current] increment_choc",
  DECREMENT_CHOC: "[current] decrement_choc",
  CHOOSE_SIZE: "[current] choose_size",
  RESET_CURRRENT: "[current] reset_current",
  CHANGE_UNITS_CURRENT: "[current] change_units",
  ADD_CART: "[cart] add_cart",
  DELETE_CART: "[cart] delete_cart",
  OPEN_CART: "[cart] open_cart",
  CLOSE_CART: "[cart] close_cart",
  CHANGE_UNITS: "[cart] change_units",
  CHOOSE_ADDRESS: "[cart] choose_address",
};
